AmmoType.register("ggs:9x39_bullets", "Base.9x39Bullets")
AmmoType.register("ggs:bullets_22LR", "Base.Bullets22LR")
AmmoType.register("ggs:bullets_32", "Base.Bullets32")
AmmoType.register("ggs:bullets_357", "Base.Bullets357")
AmmoType.register("ggs:545x39_bullets", "Base.545x39Bullets")
AmmoType.register("ggs:762x39_bullets", "Base.762x39Bullets")
AmmoType.register("ggs:762x54r_bullets", "Base.762x54rBullets")
AmmoType.register("ggs:792x57_bullets", "Base.792x57Bullets")
AmmoType.register("ggs:30_06_bullets", "Base.30_06Bullets")
AmmoType.register("ggs:303_bullets", "Base.303Bullets")
AmmoType.register("ggs:bullets_50magnum", "Base.Bullets50Magnum")
AmmoType.register("ggs:bullets_50", "Base.Bullets50")
AmmoType.register("ggs:RocketAmmo", "Base.RPG7_RocketAmmo")
AmmoType.register("ggs:GrenadeAmmo", "Base.GrenadeAmmo")
ItemTag.register("archerynexus:woodshaft_arrow")
AmmoType.register("archerynexus:woodshaft_arrow", "Base.WoodShaft_Arrow")

AmmoType.register("ggs:arrow_wood", "Base.arrow_wood")
AmmoType.register("ggs:bolt_wood", "Base.bolt_wood")
